-- transport — the ONE source for how motions reach the terminal. Each row pairs the key HS injects
-- with the tmux command it fires; on load town writes both derived artifacts (the tmux binds tmux
-- source-files, and the key manifest HS reads), so the byte HS sends and the key tmux binds can
-- never drift — they're the same fact stated once. See town-motion-model in the notes.
local HOME = os.getenv("HOME")

-- defer: the one primitive. Delegate a motion to whoever occupies the pane — if pane_current_command
-- matches `to`, hand the occupant `give`; else run `els`. vim is just one occupant; this is the
-- recursive layer-crossing (mac→tmux→vim), one `defer` per boundary. `els` can itself be a `defer`.
local function defer(to, give, els)
  return ("if -F '#{m:*%s*,#{pane_current_command}}' { send-keys %s } { %s }"):format(to, give, els)
end

local DIR = {
  h = { sel = "L", edge = "left",   of = "left-of"  },
  j = { sel = "D", edge = "bottom", of = "down-of"  },
  k = { sel = "U", edge = "top",    of = "up-of"    },
  l = { sel = "R", edge = "right",  of = "right-of" },
}
local ORDER = { "h", "j", "k", "l" }   -- deterministic, so the generated file is stable (golden-diffable)

-- point/nav: defer to vim; else cross out at the pane edge (town moves focus to the mac window),
-- else select the neighbour. the `cross-or-select` else-branch is the same delegation one layer up.
local function nav(d)
  local x = DIR[d]
  local cross = ("if -F '#{pane_at_%s}' { run-shell \"$TOWN talk future move dir=%s cross=1\" } { select-pane -%s }")
    :format(x.edge, d, x.sel)
  return defer("vim", "M-" .. d, cross)
end

-- scroll: defer to whoever owns the pane, recursively — vim (native C-d/C-u half-page), else Claude
-- Code (its own PageUp/PageDown, also half a viewport), else the pane's scrollback via copy-mode.
-- THIS is the recursive defer: one occupant per layer, each fallback is the next defer.
local function scroll(vk, cc, way)
  return defer("vim", vk, defer("claude", cc, ("copy-mode -e ; send-keys -X halfpage-%s"):format(way)))
end

-- the transport: { verb, dir, key HS injects, tmux command }. one table, two surfaces derive it.
local rows = {}
local function row(verb, dir, key, cmd) rows[#rows + 1] = { verb, dir, key, cmd } end
for _, d in ipairs(ORDER) do
  local x = DIR[d]
  row("point", d, "M-" .. d,         nav(d))                                  -- glide focus
  row("edge",  d, "M-" .. d:upper(), "resize-pane -" .. x.sel .. " 5")        -- push the wall
  row("cell",  d, "M-C-" .. d,       "swap-pane -t '{" .. x.of .. "}'")       -- carry the tile
end
row("scroll", "d", "M-d",  scroll("C-d", "NPage", "down"))   -- vim C-d / CC PageDown / copy-mode
row("scroll", "u", "M-u",  scroll("C-u", "PPage", "up"))     -- vim C-u / CC PageUp / copy-mode
row("split",  "lr", "M-%",  "split-window -h")       -- split left/right
row("split",  "tb", "M-\"", "split-window -v")       -- split top/bottom

-- derive the two artifacts. it's all tmux config syntax (source-filed, not shell), so the nested
-- if/braces/$TOWN survive verbatim; only keys holding % or " need quoting for the tmux parser.
local function tmux_key(k) return k:find("[%%\"]") and ("'" .. k .. "'") or k end

local binds = io.open(HOME .. "/.config/tmux/town-transport.conf", "w")
if binds then
  binds:write("# generated by residents/transport.lua — do not edit; edit the table there.\n")
  for _, r in ipairs(rows) do binds:write(("bind -n %s %s\n"):format(tmux_key(r[3]), r[4])) end
  binds:close()
end
local man = io.open(HOME .. "/.cache/town/transport", "w")
if man then
  for _, r in ipairs(rows) do man:write(("%s %s %s\n"):format(r[1], r[2], r[3])) end
  man:close()
end

-- hot-reload: push the regenerated binds into the live tmux NOW (no more manual `source-file`), and
-- watch tmux.conf so hand edits to it reload too — the same save-to-reload DX as the residents + HS.
-- quiet + best-effort: a no-op if tmux isn't running. (In tests os.execute is stubbed, so hermetic.)
local TMUX = (type(bins) == "table" and bins.tmux) or "tmux"
local function source(file) os.execute(TMUX .. " source-file " .. file .. " 2>/dev/null") end
source(HOME .. "/.config/tmux/town-transport.conf")   -- the binds we just wrote

return {
  watch  = { tmuxconf = HOME .. "/.config/tmux/tmux.conf" },   -- engine talks `tmuxconf` on any edit
  listen = { "tmuxconf" },
  talk   = function(w) if w.kind == "tmuxconf" then source(HOME .. "/.config/tmux/tmux.conf") end end,
}
