-- transport — the ONE source for how motions reach the terminal. Each row pairs the key HS injects
-- with the tmux command it fires; on load town writes both derived artifacts (the tmux binds tmux
-- source-files, and the key manifest HS reads), so the byte HS sends and the key tmux binds can
-- never drift — they're the same fact stated once. See town-motion-model in the notes.
local HOME = os.getenv("HOME")

-- defer: the one primitive. Delegate a motion to whoever occupies the pane — if pane_current_command
-- matches `to`, hand the occupant `give`; else run `els`. vim is just one occupant; this is the
-- recursive layer-crossing (mac→tmux→vim), one `defer` per boundary. `els` can itself be a `defer`.
local function defer(to, give, els)
  return ("if -F '#{m:*%s*,#{pane_current_command}}' { send-keys %s } { %s }"):format(to, give, els)
end

local DIR = {   -- per direction: tmux select flag · edge predicate · swap target · nvim resize char · compass · wrap target
  h = { sel = "L", edge = "left",   of = "left-of",  win = "<", compass = "w", wrap = "right"  },
  j = { sel = "D", edge = "bottom", of = "down-of",  win = "+", compass = "s", wrap = "top"    },
  k = { sel = "U", edge = "top",    of = "up-of",    win = "-", compass = "n", wrap = "bottom" },
  l = { sel = "R", edge = "right",  of = "right-of", win = ">", compass = "e", wrap = "left"   },
}
local ORDER = { "h", "j", "k", "l" }   -- deterministic, so the generated file is stable (golden-diffable)

-- point/nav: defer to vim; else, at the pane edge, wrap to the pane at the opposite edge — depth 0
-- stays strictly tmux's; reaching the mac window is the depth ladder's job (mode.lua), not nav's.
local function nav(d)
  local x = DIR[d]
  local wrap = ("if -F '#{pane_at_%s}' { select-pane -t '{%s}' } { select-pane -%s }")
    :format(x.edge, x.wrap, x.sel)
  return defer("vim", "M-" .. d, wrap)
end

-- scroll: defer to vim (native C-d/C-u half-page); anything else gets copy-mode's scrollback —
-- no per-program special cases, since a program can't be assumed to handle PageUp/PageDown.
local function scroll(vk, way)
  return defer("vim", vk, ("copy-mode -e ; send-keys -X halfpage-%s"):format(way))
end

-- the transport: { verb, dir, key HS injects, tmux command }. one table, two surfaces derive it.
local rows = {}
local function row(verb, dir, key, cmd) rows[#rows + 1] = { verb, dir, key, cmd } end
for _, d in ipairs(ORDER) do
  local x = DIR[d]
  row("point", d, "M-" .. d,         nav(d))                                  -- glide focus
  row("edge",  d, "M-" .. d:upper(),                                          -- push the wall:
    defer("vim", "5 C-w " .. x.win, "resize-pane -" .. x.sel .. " 5"))        -- the nvim split, else the pane
  row("edge-pane", d, "M-" .. x.compass, "resize-pane -" .. x.sel .. " 5")    -- push the wall, tmux only — no defer
  row("cell",  d, "M-C-" .. d,       "swap-pane -t '{" .. x.of .. "}'")       -- carry the tile
end
row("scroll", "d", "M-d",  scroll("C-d", "down"))   -- vim C-d, else copy-mode
row("scroll", "u", "M-u",  scroll("C-u", "up"))     -- vim C-u, else copy-mode
row("tab", "prev", "M-[", "previous-window")   -- tmux windows (tabs) — unconditional, no defer
row("tab", "next", "M-]", "next-window")       -- one town rung out from pane/split point-nav
row("flip",   "o", "M-o", defer("vim", "C-o", 'run-shell "$TOWN talk future back"'))     -- back: nvim jumplist, else the trail
row("flip",   "i", "M-i", defer("vim", "C-i", 'run-shell "$TOWN talk future forward"'))  -- forward: the same
row("split",  "lr", "M-%",  "split-window -h")       -- split left/right
row("split",  "tb", "M-\"", "split-window -v")       -- split top/bottom

-- derive the two artifacts. it's all tmux config syntax (source-filed, not shell), so the nested
-- if/braces/$TOWN survive verbatim; only keys holding % or " need quoting for the tmux parser.
local function tmux_key(k) return k:find("[%%\"]") and ("'" .. k .. "'") or k end

local binds = { "# generated by residents/transport.lua — do not edit; edit the table there.\n" }
for _, r in ipairs(rows) do binds[#binds + 1] = ("bind -n %s %s\n"):format(tmux_key(r[3]), r[4]) end
emit(HOME .. "/.config/tmux/town-transport.conf", table.concat(binds))

local man = {}
for _, r in ipairs(rows) do man[#man + 1] = ("%s %s %s\n"):format(r[1], r[2], r[3]) end
emit(HOME .. "/.cache/town/transport", table.concat(man))

-- hot-reload: push the regenerated binds into the live tmux NOW (no more manual `source-file`), and
-- watch tmux.conf so hand edits to it reload too — the same save-to-reload DX as the residents + HS.
-- quiet + best-effort: a no-op if tmux isn't running. (In tests os.execute is stubbed, so hermetic.)
local TMUX = (type(bins) == "table" and bins.tmux) or "tmux"
local function source(file) os.execute(TMUX .. " source-file " .. file .. " 2>/dev/null") end
source(HOME .. "/.config/tmux/town-transport.conf")   -- the binds we just wrote

return {
  watch  = { tmuxconf = HOME .. "/.config/tmux/tmux.conf" },   -- engine talks `tmuxconf` on any edit
  listen = { "tmuxconf" },
  talk   = function(w) if w.kind == "tmuxconf" then source(HOME .. "/.config/tmux/tmux.conf") end end,
}
