TMUX_DIR="$HOME/.config/tmux"

### styles

# colours
set -g @color_bg          "#1f1d20"
set -g @color_fg          "#f8f8f2"
set -g @color_subtle      "#878787"
set -g @color_active_bg   "#1f1d20"
set -g @color_active_fg   "#f92672"
set -g @color_accent      "#66d9ef"

# status bar
set -g status on
set -g status-position bottom
set -g status-style "bg=#{@color_bg},fg=#{@color_fg}"

# pane borders
set -g pane-border-style "fg=#{@color_subtle}"
set -g pane-active-border-style "fg=#{@color_accent}"

# windows 
set -g window-status-style "bg=#{@color_bg},fg=#{@color_subtle}"
set -g window-status-format " #[fg=#{@color_subtle}]#I #W "

set -g window-status-current-style "bg=#{@color_active_bg},fg=#{@color_active_fg},bold"
set -g window-status-current-format " #[fg=#{@color_active_fg},bold]#I #W* "

# memory & cpu scripts
run-shell "echo 'top -l 1 | grep -E \"^CPU\" | awk \"{print \\$3+\\$5}\"' > /tmp/tmux_cpu.sh && chmod +x /tmp/tmux_cpu.sh"
run-shell "echo 'memory_pressure | grep \"System-wide memory free percentage\" | awk \"{print 100-\\$5}\"' > /tmp/tmux_mem.sh && chmod +x /tmp/tmux_mem.sh"

# status left / right
set -g status-left "#[bg=#{@color_active_bg},fg=#{@color_active_fg},bold] #S #[default]"

set -g status-right "#[fg=#{@color_subtle}]#(echo #{pane_current_path} | sed 's#$HOME#~#g') \
#[fg=#{@color_accent}] CPU:#[fg=#{@color_fg}]#(/bin/sh /tmp/tmux_cpu.sh)% \
#[fg=#{@color_accent}] MEM:#[fg=#{@color_fg}]#(/bin/sh /tmp/tmux_mem.sh)% #[default]"

set -g status-interval 2

set -g status-left-length 30
set -g status-right-length 150

# terminal integration
set -g allow-passthrough on
set -g set-titles on
set -g set-titles-string "#S"


### main config

set -as terminal-overrides ',st*:Ss@'
set-option -sa terminal-features ',XXX:RGB'

set -g mouse on
setw -g mode-keys vi

# copy code commands
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

bind s choose-tree -sZ -O name


### session jumplist
unbind-key i
unbind-key o

bind-key o run-shell "$TMUX_DIR/scripts/session_jumplist.sh backward"
bind-key i run-shell "$TMUX_DIR/scripts/session_jumplist.sh forward"
set-hook -g client-session-changed 'run-shell "$TMUX_DIR/scripts/session_jumplist.sh record #{session_name}"'
###

# tpm
set -g @tpm_plugins ' \
	tmux-plugins/tpm \
	tmux-plugins/tmux-sensible \
	tmux-plugins/tmux-resurrect \
	christoomey/vim-tmux-navigator \
'

# order sessions by name
set -g @resurrect-processes '~Vim -> vim'

# initialize tmux plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
